console.log("bonjour datatypes");
var a;
console.log(typeof a);
var b = 2;
console.log(typeof b);
var c = "beone";
console.log(typeof c);
var d = true;
console.log(typeof d);
var obj = {};
console.log(typeof obj);
var maFonction = function () {};
console.log(typeof maFonction);
var r = [];
console.log(typeof r);
